version: "3"

services:
    gitlab:
        image: 'gitlab/gitlab-ce:${GITLAB_VERSION}'
        restart: always
        hostname: '${GITLAB_HOSTNAME}'
        container_name: ${GITLAB_CONTAINER_NAME}
        privileged: true
        environment:
            GITLAB_HOME: "${GITLAB_HOME}"
            GITLAB_OMNIBUS_CONFIG: |
                external_url="http://${GITLAB_HOSTNAME}:${GITLAB_HTTP_PORT}"
                gitlab_rails['display_initial_root_password'] = true
                gitlab_rails['store_initial_root_password'] = true
                gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
                gitlab_rails['smtp_enable'] = false
                gitlab_rails['initial_shared_runners_registration_token'] = "${GITLAB_SHARED_RUNNER_TOKEN}"
        ports:
            - ${GITLAB_HTTP_PORT}:80
            - ${GITLAB_HTTPS_PORT}:443
            - ${GITLAB_SSH_PORT}:${GITLAB_SSH_PORT}
        volumes:
            - './config:/etc/gitlab'
            - './logs:/var/log/gitlab'
            - './data:/var/opt/gitlab'
            - './secret_backups:/secret/gitlab/backups'
            - './backups:/var/opt/gitlab/backups'

