version: "3"

services:
    gitlab:
        image: 'gitlab/gitlab-ce:${GITLAB_VERSION}'
        restart: always
        hostname: '${GITLAB_HOSTNAME}'
        container_name: ${GITLAB_CONTAINER_NAME}
        privileged: true
        environment:
            GITLAB_HOME: "${GITLAB_HOME}"
            GITLAB_OMNIBUS_CONFIG: |
                external_url "${GITLAB_URI}"
                nginx['redirect_http_to_https'] = ${GITLAB_REDIRECT_HTTP_TO_HTTPS}
                gitlab_rails['display_initial_root_password'] = true
                gitlab_rails['store_initial_root_password'] = true
                gitlab_rails['smtp_enable'] = false
                gitlab_rails['initial_root_password'] = "${GITLAB_ROOT_PASSWORD}"
                gitlab_rails['initial_shared_runners_registration_token'] = "${GITLAB_SHARED_RUNNER_TOKEN}"
                nginx['ssl_certificate'] = "/etc/gitlab/ssl/${GITLAB_HOSTNAME}.crt"
                nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/${GITLAB_HOSTNAME}.key"                
                letsencrypt['enable'] = false                
        ports:
            - ${GITLAB_HTTP_PORT}:80
            - ${GITLAB_HTTPS_PORT}:${GITLAB_HTTPS_PORT}
            - ${GITLAB_SSH_PORT}:22
        dns:
            - ${GITLAB_DNS}
        volumes:
            - './config:/etc/gitlab'
            - './logs:/var/log/gitlab'
            - './data:/var/opt/gitlab'
            - './secret_backups:/secret/gitlab/backups'
            - './backups:/var/opt/gitlab/backups'
            - '${GITLAB_SSL_KEY}:/etc/gitlab/ssl/${GITLAB_HOSTNAME}.key'
            - '${GITLAB_SSL_CRT}:/etc/gitlab/ssl/${GITLAB_HOSTNAME}.crt'

